name: Push Src To apps-script Branch
on: [push]
jobs:
  Update-AS-Project:
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      id-token: 'write'
    steps:
      - name: Checkout TEST BRANCH
        uses: actions/checkout@v4
        with:
          ref: 'test-gcp'

      - name: Change js to gs
        run: find /home/runner/work/Sheets-C6-Multiplatform/Sheets-C6-Multiplatform/src -depth -name "*.js" -exec sh -c 'mv "$1" "${1%.js}.gs"' _ {} \;
       
      - name: Push To apps-script Branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: apps-script
          FOLDER: src
          TARGET_DIR: src
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Authenticate Service Account
        id: google-auth
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: 'c6-multiplatform'
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}' 
          access_token_subject: 'c9-multiplatform@berkeley.edu'
          token_format: 'access_token'
          access_token_scopes: "https://www.googleapis.com/auth/script.projects"

      - name: Push Script Code
        uses: shiftavenue/gas-action@v0
        with:
          command: push
          project-id: ${{ secrets.PROJECT_ID }}
          access-token: ${{ steps.google-auth.outputs.access_token }}
          script-dir: src