name: Push Src To apps-script Branch
on: [push]
jobs:
  Update-AS-Project:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout Main
        uses: actions/checkout@v4
        with:
          ref: 'main'

      - name: Change js to gs
        run: find /home/runner/work/Sheets-C6-Multiplatform/Sheets-C6-Multiplatform/src -depth -name "*.js" -exec sh -c 'mv "$1" "${1%.js}.gs"' _ {} \;
       
#      - name: Push To apps-script Branch
#        uses: s0/git-publish-subdir-action@develop
#        env:
#          REPO: self
#          BRANCH: apps-script
#          FOLDER: src
#          TARGET_DIR: src
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Authenticate Service Account
        id: google-auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}' 
          token_format: access_token
          access_token_scopes: "https://www.googleapis.com/auth/script.projects"

      - name: Push Script Code
        uses: shiftavenue/gas-action@v0
        with:
          # Use push command
          command: push
          project-id: ${{ secrets.PROJECT_ID }}
          access-token: ${{ steps.google-auth.outputs.access_token }}
          script-dir: src